table = {
    (((0, 0), "Clean"),): "Right",
    (((0, 0), "Clean"), ((1, 0), "Clean")): "Down",
    (((0, 0), "Clean"), ((1, 0), "Clean"), ((1, 1), "Clean")): "Left",
    (((0, 0), "Clean"), ((1, 0), "Clean"), ((1, 1), "Clean"), ((0, 1), "Clean")): "Up",
    (((1, 0), "Clean"),): "Down",
    (((1, 0), "Clean"), ((1, 1), "Clean")): "Left",
    (((1, 0), "Clean"), ((1, 1), "Clean"), ((0, 1), "Clean")): "Up",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
    ): "Right",
    (((0, 1), "Clean"),): "Up",
    (((0, 1), "Clean"), ((0, 0), "Clean")): "Right",
    (((0, 1), "Clean"), ((0, 0), "Clean"), ((1, 0), "Clean")): "Down",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
    ): "Left",
    (((1, 1), "Clean"),): "Left",
    (((1, 1), "Clean"), ((0, 1), "Clean")): "Up",
    (((1, 1), "Clean"), ((0, 1), "Clean"), ((0, 0), "Clean")): "Right",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
    ): "Down",
    (((0, 0), "Clean"), ((1, 0), "Clean"), ((1, 1), "Dirty")): "Suck",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
    ): "Up",
    (((1, 0), "Clean"), ((1, 1), "Dirty")): "Suck",
    (((1, 0), "Clean"), ((1, 1), "Dirty"), ((1, 1), "Clean")): "Left",
    (((1, 0), "Clean"), ((1, 1), "Dirty"), ((1, 1), "Clean"), ((0, 1), "Clean")): "Up",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (((1, 1), "Dirty"),): "Suck",
    (((1, 1), "Dirty"), ((1, 1), "Clean")): "Left",
    (((1, 1), "Dirty"), ((1, 1), "Clean"), ((0, 1), "Clean")): "Up",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
    ): "Up",
    (((1, 0), "Clean"), ((1, 1), "Clean"), ((0, 1), "Dirty")): "Suck",
    (((1, 0), "Clean"), ((1, 1), "Clean"), ((0, 1), "Dirty"), ((0, 1), "Clean")): "Up",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
    ): "Right",
    (((0, 1), "Dirty"),): "Suck",
    (((0, 1), "Dirty"), ((0, 1), "Clean")): "Up",
    (((0, 1), "Dirty"), ((0, 1), "Clean"), ((0, 0), "Clean")): "Right",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
    ): "Left",
    (((1, 1), "Clean"), ((0, 1), "Dirty")): "Suck",
    (((1, 1), "Clean"), ((0, 1), "Dirty"), ((0, 1), "Clean")): "Up",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
    ): "Suck",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (((1, 1), "Dirty"), ((1, 1), "Clean"), ((0, 1), "Dirty")): "Suck",
    (((1, 1), "Dirty"), ((1, 1), "Clean"), ((0, 1), "Dirty"), ((0, 1), "Clean")): "Up",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
    ): "Down",
    (((0, 0), "Clean"), ((1, 0), "Dirty")): "Suck",
    (((0, 0), "Clean"), ((1, 0), "Dirty"), ((1, 0), "Clean")): "Down",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
    ): "Up",
    (((1, 0), "Dirty"),): "Suck",
    (((1, 0), "Dirty"), ((1, 0), "Clean")): "Down",
    (((1, 0), "Dirty"), ((1, 0), "Clean"), ((1, 1), "Clean")): "Left",
    (((1, 0), "Dirty"), ((1, 0), "Clean"), ((1, 1), "Clean"), ((0, 1), "Clean")): "Up",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
    ): "Right",
    (((0, 1), "Clean"), ((0, 0), "Clean"), ((1, 0), "Dirty")): "Suck",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
    ): "Up",
    (((1, 0), "Dirty"), ((1, 0), "Clean"), ((1, 1), "Dirty")): "Suck",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
    ): "Suck",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
    ): "Suck",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
    ): "Suck",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (((0, 0), "Dirty"),): "Suck",
    (((0, 0), "Dirty"), ((0, 0), "Clean")): "Right",
    (((0, 0), "Dirty"), ((0, 0), "Clean"), ((1, 0), "Clean")): "Down",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (((0, 1), "Clean"), ((0, 0), "Dirty")): "Suck",
    (((0, 1), "Clean"), ((0, 0), "Dirty"), ((0, 0), "Clean")): "Right",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
    ): "Left",
    (((1, 1), "Clean"), ((0, 1), "Clean"), ((0, 0), "Dirty")): "Suck",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (((0, 1), "Dirty"), ((0, 1), "Clean"), ((0, 0), "Dirty")): "Suck",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Clean"),
    ): "Down",
    (((0, 0), "Dirty"), ((0, 0), "Clean"), ((1, 0), "Dirty")): "Suck",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
    ): "Suck",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
    ): "Suck",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
    ): "Up",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
    ): "Right",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
    ): "Suck",
    (
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
    ): "Left",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
    ): "Suck",
    (
        ((1, 1), "Dirty"),
        ((1, 1), "Clean"),
        ((0, 1), "Dirty"),
        ((0, 1), "Clean"),
        ((0, 0), "Dirty"),
        ((0, 0), "Clean"),
        ((1, 0), "Dirty"),
        ((1, 0), "Clean"),
    ): "Down",
}
